### ISSUE TITLE
OpenCV binaries fail to load

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [JohnSnowLabs/spark-ocr-workshop#81]
This started to happen randomly in different platforms(Databricks and Colab), it seems we depend on the opencv binary to be present in the platform(as a native lib) to be able to load open cv.
We should instead depend also on the binary shipped within our jar, which we probably should get from(this is in the classpath)

opencv-4.3.0-1.5.3-linux-x86.jar

but we apparently don't ship(may be an assembly issue?)

_Error_
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:431)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$toLocalIteratorAndServe$2(PythonRDD.scala:327)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1626)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$toLocalIteratorAndServe$1(PythonRDD.scala:345)
	at org.apache.spark.api.python.PythonRDD$.$anonfun$toLocalIteratorAndServe$1$adapted(PythonRDD.scala:296)
	at org.apache.spark.security.SocketFuncServer.handleConnection(SocketAuthServer.scala:115)
	at org.apache.spark.security.SocketFuncServer.handleConnection(SocketAuthServer.scala:108)
	at org.apache.spark.security.SocketAuthServer$$anon$1.$anonfun$run$1(SocketAuthServer.scala:62)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.security.SocketAuthServer$$anon$1.run(SocketAuthServer.scala:62)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 4 times, most recent failure: Lost task 0.3 in stage 5.0 (TID 1310, 10.164.248.13, executor 22): java.lang.UnsatisfiedLinkError: no opencv_java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.opencv.osgi.OpenCVNativeLoader.init(OpenCVNativeLoader.java:15)
	at org.dcm4che3.opencv.StreamSegment.<clinit>(StreamSegment.java:76)
	at org.dcm4che3.opencv.NativeJPEGImageReaderSpi.canDecodeInput(NativeJPEGImageReaderSpi.java:92)
	at javax.imageio.ImageIO$CanDecodeInputFilter.filter(ImageIO.java:567)
	at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:834)
	at javax.imageio.spi.FilterIterator.next(ServiceRegistry.java:852)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:528)
	at javax.imageio.ImageIO$ImageReaderIterator.next(ImageIO.java:513)
	at com.johnsnowlabs.ocr.transformers.BinaryToImage.$anonfun$transformUDF$2(BinaryToImage.scala:30)
	at scala.util.Try$.apply(Try.scala:213)
	at com.johnsnowlabs.ocr.transformers.BinaryToImage.$anonfun$transformUDF$1(BinaryToImage.scala:26)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.generate_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:733)
	at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anon$1.hasNext(InMemoryRelation.scala:132)
	at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
	at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)

**Comment by kolia1985** [comment]
This related to the some image format.

We have preset opencv inside our jar, but I'm not sure that it is compatible with imageIo plugin.

For start please share image for reproduce error.

**Comment by albertoandreottiATgmail** [comment]
hi thanks @kolia1985 and @xyutech , it seems the problem was present in my local environment only(with jars produced there).
Closing now.
